from __future__ import annotations


def build_review_prompt(*, task_prompt: str | None = None) -> str:
    task_section = ""
    if task_prompt and task_prompt.strip():
        task_section = (
            "\n"
            "# TASK INSTRUCTIONS (SOURCE OF TRUTH)\n"
            "\n"
            f"{task_prompt.strip()}\n"
        )

    return (
        "# ROLE\n"
        "\n"
        "You are reviewing the current repository state BEFORE submitting a PR.\n"
        "\n"
        "# REVIEW SCOPE (CRITICAL)\n"
        "\n"
        "Review the ENTIRE set of changes that will end up in the PR: both the committed branch diff\n"
        "AND any currently uncommitted changes.\n"
        "\n"
        "Start with the branch diff (what the PR will contain):\n"
        "- `git diff origin/main...HEAD`\n"
        "\n"
        "Then include any uncommitted work:\n"
        "- `git status`\n"
        "- `git diff`\n"
        "\n"
        "# WORKFLOW CONTEXT\n"
        "\n"
        "- Do NOT require changes to be staged. The submit step will stage everything automatically.\n"
        "- Consider the ENTIRE changeset that will be included in the PR, not just uncommitted files.\n"
        "\n"
        "# REVIEW RULES\n"
        "\n"
        "- Treat the Task instructions (if provided below) as the source of truth.\n"
        "- Only require changes if they are necessary for correctness, security (no leaked secrets/tokens),\n"
        "  or to satisfy explicit requirements in the Task instructions.\n"
        "- Do not request stylistic refactors or generic best-practice changes unless explicitly required.\n"
        "- Example: flag unintended generated/build artifacts that got staged/committed (e.g. build outputs,\n"
        "  dependency directories, caches). Require reverting them and/or adding correct `.gitignore` rules.\n"
        "\n"
        "# CODE COMMENTS (CRITICAL)\n"
        "\n"
        "As part of reviewing the full branch diff, inspect ALL added/modified code comments.\n"
        "If any comments are redundant, narrative, or simply restate what the code does,\n"
        "you MUST flag them and require removing/replacing them.\n"
        "Comments should exist only when absolutely required for essential non-obvious information.\n"
        f"{task_section}\n"
        "\n"
        "# PERMITTED ACTIONS\n"
        "\n"
        "You may run any relevant commands (e.g. git status, git diff, git log, tests) and read files.\n"
        "If changes are needed before submitting, list them clearly.\n"
        "\n"
        "# IMPORTANT OUTPUT FORMAT (NO EXTRA TEXT)\n"
        "\n"
        "- If the repo is ready, output exactly: READY_TO_COMMIT\n"
        "- Otherwise output exactly: CHANGES_REQUIRED\\n<bullet list of required changes>\n"
    )
